name: Generate Fabrication Files

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  kibot:
    runs-on: ubuntu-latest
    container:
      # Korrekter Name des Docker-Images
      image: setsoft/kibot-automation:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run KiBot
        run: |
          # Wir nutzen Platzhalter (*), damit der Dateiname egal ist
          kibot -c config.kibot.yaml -b *.kicad_pcb -e *.kicad_sch

      - name: Upload Fabrication Folder
        uses: actions/upload-artifact@v4
        with:
          name: Fabrication-Data-${{ github.ref_name }}
          path: Fabrication/